---
name: Pod-POM-View-SPIP
version: 0.03
author:
  - Jérôme Fenal E<lt>jfenal@free.frE<gt>
abstract: POD Object Model View for SPIP
license: perl
requires:
  Pod::POM: 0
recommends:
  Test::More: 0
provides:
  Pod::POM::View::SPIP:
    file: lib/Pod/POM/View/SPIP.pm
    version: 0.03
generated_by: Module::Build version 0.2611
