# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-POM-View-SPIP
version:      0.01
version_from: 
installdirs:  site
requires:
    Pod::POM:                      

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
